plugins {
    id 'com.android.application'
}

android {
    namespace 'com.romanticcenter.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.romanticcenter.app"
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName "3.2.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.9.1'
}
