plugins {
    id 'com.android.application'
}

android {
    namespace 'com.romanticcenter.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.romanticcenter.app"
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName "2.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}

dependencies {
}
