name: mizancode
publish_to: 'none'
description: MizanCode unified Flutter client for business and loyalty.
version: 4.1.0+41

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  mobile_scanner: ^7.1.2
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
